name: Build & Test CashOverflow
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v2
    - name: Installing .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.201
        include-prerelease: false
    - name: Restoring packages
      run: dotnet restore
    - name: Building project
      run: dotnet build --no-restore
    - name: Running tests
      run: dotnet test --no-build --verbosity normal
